// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksfzvmdiaobrgzzldgxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzZnp2bWRpYW9icmd6emxkZ3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMjI2OTQsImV4cCI6MjA3Mjc5ODY5NH0.KR9bryO7tcqboC-ebeug3s7SygDySrLAgSfhio5QqRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});